# network
bind 0.0.0.0
port 6379

# docker logging
daemonize no
logfile   ""
loglevel  notice


# RDB
# RDB: save every hour if at least 1 change
save 3600 1
# RDB: save every 5 min if at least 100 changes
save 300 100
# RDB: save every minute if 10000 changes
save 60 10000

# AOF
appendonly  yes
appendfsync everysec

# memory management
maxmemory        100mb
maxmemory-policy allkeys-lru

# user management
# user username on/off password permission
user default off
# superuser
user superuser on >admin ~* &* +@all
# normal user
user aqilknz on >pass123 resetchannels ~aqilknz:* +@string